FROM golang:1.25.0-alpine AS go-builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -a -installsuffix cgo -o /kafka-producer ./cmd/producer-service/main.go

FROM alpine:3.22

COPY --from=go-builder /kafka-producer /kafka-producer

ENTRYPOINT ["/kafka-producer"]