# volumes/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081'] # Обращаемся к сервису 'app' по порту метрик