REVOKE ALL PRIVILEGES ON TABLE items FROM admin;
REVOKE ALL PRIVILEGES ON TABLE payment FROM admin;
REVOKE ALL PRIVILEGES ON TABLE delivery FROM admin;
REVOKE ALL PRIVILEGES ON TABLE orders FROM admin;