GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE orders TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE delivery TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE payment TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE items TO admin;
